### ISSUE TITLE
Use token-based registration

### ISSUE THREAD

**Issue by strugee** [SeaGL/attend.seagl.org#24]
Resources:

- https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/registration_tokens.html
- https://spec.matrix.org/v1.4/client-server-api/#token-authenticated-registration
- https://github.com/vector-im/element-web/issues/18931

**Comment by AndrewKvalheim** [comment]
I don’t see how this is supposed to work. `m.login.registration_token` requires a `session` but there is no session prior to registration, and `m.login.registration_token` can only be used on `/register`.
