### ISSUE TITLE
post-ephemeral user creation screen updates

### ISSUE THREAD

**Issue by altsalt** [SeaGL/attend.seagl.org#25]
Right now once you create an ephemeral account it pops up a survey window that should be removed/modified. It says "Who will you chat to the most?" Screenshot attached.

![image](https://user-images.githubusercontent.com/2441328/199890348-8204ee83-7f43-4a1d-9c81-9612d28b8985.png)

Related, but probably separate, the initial space is 404'ing after clicking skip.
`MatrixError: [404] Not Found (https://matrix.2022.seagl.org/_matrix/client/r0/join/%232022%3Aseagl.org)`

![image](https://user-images.githubusercontent.com/2441328/199890472-916ca2dd-f9d8-4938-8b52-13f3cf729653.png)

**Comment by AndrewKvalheim** [comment]
Resolved by 475205b and 3430dcf
