### ISSUE TITLE
Update 2023 message

### ISSUE THREAD

**Issue by strugee** [SeaGL/attend.seagl.org#29]
I just fully destroyed the server - the off-season message needs updating. Looks like that branch hasn't been pushed.

**Comment by AndrewKvalheim** [comment]
I just ran [`make down`](https://github.com/SeaGL/attend.seagl.org/blob/234399d0735bb0ea813fc631b574a61489729df7/Makefile#L5-L8) and [deployed](https://github.com/SeaGL/attend.seagl.org/issues/3). Does some content still need updating?

**Comment by strugee** [comment]
I think I just misunderstood your branching scheme lol
