### ISSUE TITLE
Ability to specify an automatically used login/password in the URL

### ISSUE THREAD

**Issue by strugee** [SeaGL/attend.seagl.org#32]
Basically, I want to be able to open a URL from a shell script, and have it automatically trigger authentication in the attend portal.

**Comment by AndrewKvalheim** [comment]
This might be more work to implement than it’s worth. Can you provision a saved password in the browser?

**Comment by strugee** [comment]
Not sure, I hadn't thought about that before. I'd have to investigate how tricky the format is.

**Comment by AndrewKvalheim** [comment]
Turns out this functionality already existed for authentication tokens so it wasn’t much trouble to add a password option.

Thinking about this now though, perhaps we should actually scrap this and just use tokens since they’re better fit for this type of usage anyway.
