### ISSUE TITLE
Branding of Element

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/attend.seagl.org#6]
Change the colors and logos in Element to match SeaGL’s branding.

**Comment by altsalt** [comment]
Just wanted to toss this in here. Doubt we need to go as far as some of what is being suggested, but it is a good set of considerations:
https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1387#issuecomment-964211067

**Comment by AndrewKvalheim** [comment]
Decided against this; we prefer to downplay the custom client and instead promote longer term adoption of Matrix.
